# Site settings
title: Sortica
email: your-email@example.com
description: >-
  Sortica - Algorithmic Inventory Sorter. A Serious Game for...
baseurl: "/sortica"
url: "https://frankoldfield.github.io/"
twitter_username: 
github_username: frankoldfield

# Build settings
# CAMBIO IMPORTANTE: Ya no usamos remote_theme, sino el tema como gem
# Nota: Minimal Mistakes versión 4.27.3 (última disponible)
minimal_mistakes_skin: dark

head_scripts:
  - https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap
  - https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400;500;600&display=swap

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-spaceship
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# Configuración de jekyll-spaceship para Mermaid
jekyll-spaceship:
  mermaid-processor:
    mode: pre-fetch

include: ["_pages"]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE